Added scripts execution

diff --git a/.github/workflows/scrapers_runner.yml b/.github/workflows/scrapers_runner.yml
--- a/.github/workflows/scrapers_runner.yml
+++ b/.github/workflows/scrapers_runner.yml
@@ -27,6 +27,13 @@ jobs:
         pip3 install -r requirements.txt
         sudo apt-get install curl
         
+    - name: All scrapers run
+      env:
+        API_KEY: ${{ secrets.API_KEY }}
+      run: |
+        python3 sites/script_runner.py || true
+        echo "Continuing despite potential failure..."
+        
     - name: Set up Java
       uses: actions/setup-java@v2
       with:
